POST http://localhost:3003/api/blogs
Content-Type: application/json

{
"title": "All Sports United", 
"author": "Kirk McMahon",
"url": "web-page-1234567890",
"likes": 45432,
"userId": "68c6a3b625d997a97caa3df1"
}
